// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFADQjXGLHe2ip6mo2B0netwyj6Fg9bn4',
    appId: '1:280933866764:web:8a876649975fd694e8bd29',
    messagingSenderId: '280933866764',
    projectId: 'firestorecrud-82192',
    authDomain: 'firestorecrud-82192.firebaseapp.com',
    storageBucket: 'firestorecrud-82192.appspot.com',
    measurementId: 'G-J9YDXRLZ96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1XFvsDOb-euc-_9dZZ9ZsAiAV1uaK-vg',
    appId: '1:280933866764:android:acd69a65296376fde8bd29',
    messagingSenderId: '280933866764',
    projectId: 'firestorecrud-82192',
    storageBucket: 'firestorecrud-82192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHO5oV3xk4T4HU8AyKXCz-ETyIAKzOXec',
    appId: '1:280933866764:ios:d97c491c8a85c980e8bd29',
    messagingSenderId: '280933866764',
    projectId: 'firestorecrud-82192',
    storageBucket: 'firestorecrud-82192.appspot.com',
    iosClientId: '280933866764-egg7ft51e13h98dpisulipiv4qggkr6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHO5oV3xk4T4HU8AyKXCz-ETyIAKzOXec',
    appId: '1:280933866764:ios:d97c491c8a85c980e8bd29',
    messagingSenderId: '280933866764',
    projectId: 'firestorecrud-82192',
    storageBucket: 'firestorecrud-82192.appspot.com',
    iosClientId: '280933866764-egg7ft51e13h98dpisulipiv4qggkr6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCrud',
  );
}
